name: Build APK on Commit

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JBR 17
        run: |
          wget https://download.jetbrains.com/java/JBR-17.0.2_8_17.0.2-linux-x64.tar.gz
          tar -xzf JBR-17.0.2_8_17.0.2-linux-x64.tar.gz
          export PATH=$PATH:$PWD/jbr-17.0.2_8/bin/

      - name: Build APK
        run: |
          java -version
          chmod +x gradlew
          ./gradlew assembleDebug --info

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

